# This file was generated by GoReleaser. DO NOT EDIT.
class Devenv < Formula
  desc ""
  homepage "https://github.com/endorama/devenv"
  version "1.0.0-beta.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/endorama/devenv/releases/download/1.0.0-beta.4/devenv_1.0.0-beta.4_macOS_64bit.tar.gz"
    sha256 "44809a45838eecacc35f74e2ba9a43e1595d53b42449004cda6075ea4e191b8e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/endorama/devenv/releases/download/1.0.0-beta.4/devenv_1.0.0-beta.4_Linux_64bit.tar.gz"
      sha256 "4165bfaa80892da5f5bb6eb4a97034ecd55ebc3a4e69e22c2da1eda7ca3060a9"
    end
  end

  def install
    bin.install "devenv"
  end

  test do
    system "#{bin}/devenv --version"
  end
end
